version: '3.8'

services:
  db:
    build: .
    container_name: marketplace_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: marketplace
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./sample_data.sql:/docker-entrypoint-initdb.d/02-sample_data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d marketplace"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: marketplace_api
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: marketplace
      DB_USER: admin
      DB_PASSWORD: admin123
      API_HOST: 0.0.0.0
      API_PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app:ro

  adminer:
    image: adminer:latest
    container_name: marketplace_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
